### ISSUE TITLE
Support externalTrafficPolicy: Local

### ISSUE THREAD

**Issue by loganmc10** [k3s-io/klipper-lb#14]
When using klipper-lb, even when setting ```externalTrafficPolicy: Local```, the source IP shows as ```172.16.18.1``` (the first IP in the cluster cidr range).

It would be nice if it could preserve the IP address of the client, useful for when you need to do a reverse DNS lookup of the client ip

**Comment by comphilip** [comment]
@loganmc10 Klipper-lb does not change source IP. it supports `externalTrafficPolicy: Local`.  I tried https://comphilip.wordpress.com/2021/05/23/k3s-thing-make-traefik-forward-real-client-ip/
