### ISSUE TITLE
How to disable KlipperLB from Nginx Ingress?

### ISSUE THREAD

**Issue by tekspacedemo** [k3s-io/klipper-lb#7]
Hi, I installed Nginx Ingress by using helm chart to my k3s cluster. It enabled KlipperLB on all of my node and I would like to disable it so that I can use ingress with my external LB. Please let me know what info I need to provide to able to get further assistance?

**Comment by TheYkk** [comment]
`--disable servicelb`

**Comment by tekspacedemo** [comment]
Thanks @TheYkk for your response. So I guess I need to apply that arg at the cluster setup step? Is there a way to disable that after cluster is setup? I dont want to tear down the cluster and rebuild it.

**Comment by TheYkk** [comment]
You can add this flag to your cluster setup script. In k3s upgrading, the cluster will not break your cluster

**Comment by tekspacedemo** [comment]
Okay. So you are saying, if I execute below command on my master node that is running the cluster, it will simply disable `klipperlb` and not break the cluster? 

`curl -sfL https://get.k3s.io | sh -s - server --disable servicelb`

**Comment by TheYkk** [comment]
It will be brek your load balancers but, you can fix by installing other load balancer solutions.

If you setup cluster with `curl -sfL https://get.k3s.io | sh`  it's not gonna break the cluster but if you applied some flags on cluster setup you have to write again as flag

**Comment by tekspacedemo** [comment]
Okay. I will give that a try. As long as it will disables below `controllers` I should be fine. Thanks for looking into this.

`svclb-home-ingress-nginx-controller-2nh5x        2/2     Running   0          18h
svclb-home-ingress-nginx-controller-ft9x9        2/2     Running   0          18h
svclb-home-ingress-nginx-controller-ggvkk        2/2     Running   0          18h`

**Comment by rthamrin** [comment]
1. if you start to install your k3s and want to disable the Traefik and Klipper 

`# curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable=traefik --disable=servicelb" sh –`


2. the second way is to go to edit your file using nano or vim
**#/etc/systemd/system/k3s.service**

int the last line u can add

```
ExecStart=/usr/local/bin/k3s \
    server \
        '--disable=traefik' \
        '--disable=servicelb' \
```

3. you may also try this

ExecStart=/usr/local/bin/k3s server --disable servicelb --disable traefik

after you add the line don't forget to restart the daemon of the K3S 

```
systemctl daemon-reload
systemctl restart k3s.service
```
